# @name login
POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin@figurinhas.com",
    "password": "admin"
}

###

@authToken = {{login.response.body.access_token}}

###

DELETE http://localhost:3333/user/6 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}
