name: deploy-prd
on:
  push:
    branches: [main]
jobs:
  checkout:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Realiza a instalação das dependências
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: |
          cd web
          yarn install --frozen-lockfile --production=false
          cd ../
          cd api
          yarn install --frozen-lockfile --production=false
  build:
    name: Cria a imagem Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           builder: ${{ steps.buildx.outputs.name }}
#           context: .
#           platforms: linux/amd64
#           push: true
#           cache-from: type=local,src=/tmp/.buildx-cache
#           cache-to: type=local,dest=/tmp/.buildx-cache
#           tags: ghcr.io/bankme-tech/api-bankme:latest

#   deploy:
#     name: Realiza o deploy
#     runs-on: prd
#     needs:
#       - test
#       - build

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Deploy da API Bankme de produção
#         run: |
#           cd /home/ubuntu/api-bankme
#           cp $GITHUB_WORKSPACE/docker-compose.yml docker-compose.yml
#           docker pull ghcr.io/bankme-tech/api-bankme:latest
#           docker service update --image ghcr.io/bankme-tech/api-bankme api-bankme_nest-app --force
#           docker service update --force api-bankme_nginx-proxy

# #          docker stack deploy -c <(docker-compose --env-file .env.production config) api-bankme
